### ISSUE TITLE
get DataColletions bad result

### ISSUE THREAD

**Issue by mgaonach** [ispyb/py-ispyb#118]
There is an issue with the get method on DataColletions: the returned result always is an object with only null fields.

When I comment the following line in DataColletions.get (pyispyb/core/routes/data_collections.py), I get a correct result:
_@api.marshal_list_with(data_collection_schemas.f_schema, skip_none=False, code=HTTPStatus.OK)_

**Comment by IvarsKarpics** [comment]
Hi @mgaonach 

Mashal_with decorator defines the output data structure. skip_none=False means that also variables with null value will be returned. If its True then resulting dictionary should not include null variables. I think in this case we should not use decorator, because we will return a custom dictionary. I will check this.
