### ISSUE TITLE
Supporting different databases

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#133]
I was thinking one way to support dls and esrf database structures would be to create two new packages
* `ispyb-models-dls`
* `ispyb-models-pydb`

which both provide `ispyb.models`, pyispyb should depend on one of these being installed. By installing the right one you get the relevant models.

These two packages can build the sqlalchemy models automatically in CI from the relevant database structures, for dls there is already a github workflow (azure, needs to be converted):
https://github.com/DiamondLightSource/ispyb-api/blob/master/.azure-pipelines/update-orm.yml
https://github.com/diamondlightsource/ispyb-database

I suggest extracting the pydb sql definitions out of the java project into a new project.

`ispyb-models-dls` provides `ispyb.models` -> generated from https://github.com/diamondlightsource/ispyb-database
`ispyb-models-pydb` provides `ispyb.models` -> generated from `ispyb/pydb` (new project)

Or we could generate both within py-ispyb CI and select with an env var?

We can also build docker containers based on each of the packages.
In the long term we should aim to remerge (they are not a million miles away)

Thoughts @mgaonach ?

**Comment by antolinos** [comment]
I think we should focus on the official database version that is used for most of the sites. There are already enough challenges (and work) in front of us.
If our colleagues of DLS wants to implement this enhancement to make their DB compatible then why not. This is so specific that this should be addressed by them.

Cheers!

**Comment by rjgildea** [comment]
I think coming up with a mechanism to support multiple database "flavours" where possible would be critical to maintain DLS involvement in this project. Given we already have [auto-generated SQLAlchemy models](https://github.com/DiamondLightSource/ispyb-api/blob/master/src/ispyb/sqlalchemy/_auto_db_schema.py) for our flavour of ISPyB, perhaps it would be possible to some how make use of this directly, rather than having to maintain a separate (but otherwise identical) set of models?

**Comment by stufisher** [comment]
I think its technically reasonably easy. ispyb-api could provide `ispyb.models`, then we just need another package ispyb-pydb or something to provide the ESRF models.

We now have docker containers for DLS, and ESRF dbs which means we can test against both in CI, and if we are clever in endpoint design we can probably deal with minor differences. Most of the differences from my quick scan are extra columns and tables in the DLS flavour, we should be able to pytest skip if running ESRF flavour.

**Comment by antolinos** [comment]
If there are only some extra columns and tables, it is maybe worth to merge them in a single model than having to support both. 
It will definitively simplify developments and make easier in terms of collaboration. 
We already saw that nothing good comes from having two data models.

**Comment by stufisher** [comment]
Merging the schemas is absolutely the best outcome. I wasn't sure what your feelings were on this. 

The DLS schema is ahead of pydb by some columns and tables from my initial investigation. I think we could generate a script to bring pydb up to the features of the DLS schema. An outstanding area is that EM is still diverged, one facility will have to change their column naming in DataCollection (@olofsvensson, @JPHall-DLS)

Then a possibility (with @KarlLevik's blessing) could be to move https://github.com/diamondlightsource/ispyb-database into the ISPyB repository, and this be used as the reference database. Karl has nicely setup the tables, data, lookups, etc separately with relevant ci to generate documentation automatically. This also makes it easier to setup a clean db for testing etc.

In the short term i think we can support both databases (temporarily, with minimal code impact) until the schemas are merged.

**Comment by antolinos** [comment]
Definitely, I'd not go for two databases and I do not think we should support two databases even in the short term. The reason is because we have worked with two databases in the past and  was demonstrated not to be very successful and/or efficient in terms of collaboration.

We should also agree that the reference database is the one from ISPyB and the one that will be used by `py-ispyb`. DLS can propose these changes and work in order to make them compatible. As most of the facilities are running in ISPyB in production we should also evaluate what these changes mean in terms of work and how this fits in our priorities. 

I remind you that the short term goal is to get SSX done. That was agreed and should be respected as much as possible.

Our medium term goal is to smoothly replace `ISPyB` by `py-ispyb` but we expect to use both simultaneously on the same database until full replacement is done. I think it is a goal shared by most of the facilities. Therefore, having ISPyB in production with the reference database whilst py-ispyb uses the DLS-flavour does not sound good to me.

I think it is a subject important enough to be added in the next meeting agenda.
