### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by mgaonach** [ispyb/py-ispyb#142]
We currently have two naming conventions in the code

1. snake case (python standard) 
2. mixed case (used to refer to DB columns names) - see #135 

The linting for variable names has been deactivated (see #137 ) to cope with this difference.

We need to enforce a standard through linting so that the code does not become a mix of everything after some time.

We need to decide with the collaboration to either :

- Enforce python standard snake case everywhere, and decouple code naming from db names
- Override python standard and enforce mixed case everywhere, and thus have a consistent convention in db, backend and frontend (is there a flake8 plugin to do so?)

**Comment by mgaonach** [comment]
@stufisher @antolinos

**Comment by stufisher** [comment]
See https://github.com/ispyb/py-ispyb/pull/135#issuecomment-1109175391 for relevant discussion
cc @JPHall-DLS @KarlLevik

**Comment by KarlLevik** [comment]
It feels wrong to violate the Python standard, but based on my own experiences, it's an even worse developer experience to decouple code naming from names in the database.

We could of course rename the actual names in the database, but that would break existing code and would mean a major effort all around. Since that is unrealistic due to the effort required, then I agree with James in the comment linked to above.

**Comment by rjgildea** [comment]
I agree with @KarlLevik that it would be vastly preferable to decrease the cognitive load of developers by only requiring them to maintain in their head one set of database naming conventions. And from the API user point of view, the naming convention of fields provided by the API shouldn't necessarily be determined by the naming conventions of the language used to develop the API.

I don't think this necessarily means we should have to exclusively use camelCase elsewhere outside of names that are defined by their database equivalents.
